site_name: ML Blog
site_url: https://mauriciolucas22.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:

    # Defina o modo escuro como padrão
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo Escuro

    # Botão de alternância para o modo claro
    - toggle:
        icon: material/brightness-7
        name: Modo Claro

    # Botão de alternância para o modo escuro
    - toggle:
        icon: material/brightness-4
        name: Modo Escuro

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mauriciolucas22
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mauricio-lucas

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/mauriciolucas22"  target="_blank" rel="noopener">Mauricio Lucas</a>
